### PR TITLE
End of input error iter 0

### PR DESCRIPTION
**Pull request by weilandia**

### CODE REVIEW

**Comment by jcasimir** [comment]
Looks good but I'll let @applegrain take a look.

**Comment by biglovisa** [comment]
Thanks @weilandia! 

The `sales_analyst` shouldn't actually be required on the top level. The `SalesEngine` can exist without the `sales_analyst` but the `sales_analyst` is dependent on the `SalesEngine` to exist.

Could you please remove it from the `spec_helper.rb` as well as the `pry` that's left in the spec file? You can make the changes on your branch and the PR will update when you push.

**Comment by weilandia** [comment]
@applegrain I agree--Wouldn't this mean that we would need to require 'sales_analyst' in the spec in order for the test that's copied below to run?  Otherwise, we'd have to require 'sales_analyst' in our 'sales_engine' file...

``````
 context "Sales Analyst" do
    let(:sales_analyst) { SalesAnalyst.new(engine) }

    it "#average_items_per_merchant returns average items per merchant" do
      expected = sales_analyst.average_items_per_merchant

      expect(expected).to eq 2.87
      expect(expected.class).to eq Float
    end```
``````

**Comment by weilandia** [comment]
Waiting for update to send new pull

**Pull request closed without merging**
